# Generated by Django 3.2.4 on 2021-06-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["accession_id"],
            },
        ),
        migrations.CreateModel(
            name="ImageMetadataDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata_value", models.CharField(max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_metadata",
                        to="api.image",
                    ),
                ),
                (
                    "metadata_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.imagemetadatadict",
                    ),
                ),
            ],
            options={
                "ordering": ["image", "metadata_key__key"],
                "unique_together": {("image", "metadata_key")},
            },
        ),
    ]
