# Generated by Django 3.2.4 on 2021-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="accession_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
